
/* Exit Status */
#define STATUS_OK 0
#define STATUS_WARNING 1
#define STATUS_CRITICAL 2
#define STATUS_UNKNOWN 3

#define MAX_ENTRIES 128
#define MAX_OCTETSTRING_LEN 255
#define MAX_OCTETSTRING_128_LEN 128
#define MAX_OCTETSTRING_64_LEN 64
